name: Complete Multi-Platform Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-all:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: android
            build-command: flutter build apk --release --no-tree-shake-icons && flutter build appbundle --release --no-tree-shake-icons
            artifact-name: Android-Release
            artifact-path: build/app/outputs/
          - os: ubuntu-latest
            platform: web
            build-command: flutter build web --release --no-tree-shake-icons
            artifact-name: Web-Release
            artifact-path: build/web/
          - os: macos-14
            platform: ios
            build-command: flutter build ios --no-codesign --release --no-tree-shake-icons
            artifact-name: iOS-Release
            artifact-path: build/ios/iphoneos/
            
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Java (Android only)
      if: matrix.platform == 'android'
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.2'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Generate code
      run: flutter packages pub run build_runner build --delete-conflicting-outputs
      
    - name: Analyze code
      run: flutter analyze --no-fatal-infos
      
    - name: Run tests
      run: flutter test
      
    - name: Build for ${{ matrix.platform }}
      run: ${{ matrix.build-command }}
      
    - name: Create IPA (iOS only)
      if: matrix.platform == 'ios'
      run: |
        mkdir -p Payload
        cp -r build/ios/iphoneos/Runner.app Payload/
        zip -r TasteSmoke-iOS-${{ github.ref_name }}.ipa Payload/
        
    - name: Create Web package (Web only)
      if: matrix.platform == 'web'
      run: |
        cd build/web
        tar -czf ../../TasteSmoke-Web-${{ github.ref_name }}.tar.gz .
        
    - name: Upload iOS IPA
      if: matrix.platform == 'ios'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact-name }}
        path: TasteSmoke-iOS-${{ github.ref_name }}.ipa
        retention-days: 90
        
    - name: Upload Web package
      if: matrix.platform == 'web'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact-name }}
        path: TasteSmoke-Web-${{ github.ref_name }}.tar.gz
        retention-days: 90
        
    - name: Upload Android artifacts
      if: matrix.platform == 'android'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact-name }}
        path: |
          build/app/outputs/flutter-apk/app-release.apk
          build/app/outputs/bundle/release/app-release.aab
        retention-days: 90
        
  create-release:
    needs: build-all
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Android-Release/*
          Web-Release/*
          iOS-Release/*
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}