name: Build Web App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.2'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Generate code
      run: flutter packages pub run build_runner build --delete-conflicting-outputs
      
    - name: Build Web
      run: flutter build web --release --no-tree-shake-icons
      
    - name: Create deployment package
      run: |
        cd build/web
        tar -czf ../../TasteSmoke-Web.tar.gz .
        
    - name: Upload Web artifact
      uses: actions/upload-artifact@v4
      with:
        name: TasteSmoke-Web
        path: TasteSmoke-Web.tar.gz
        retention-days: 30
        
    # Опционально: деплой на GitHub Pages
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web